### ISSUE TITLE
Support cognitive / willpower availability

### ISSUE THREAD

**Issue by cathywu** [cathywu/TimeAlloc#94]
## Design decisions

- **Cognitive affinity**: goal is to exploit the cognitive energy structure of the week to encourage doing tasks at cognitively appropriate times.
- **Willpower balance**: goal is to allow monitoring of willpower balance, and avoid willpower depletion. Also referred to as ego depletion.

## Can also consider

- Mental energy -- this would be the willpower balance analog to the cognitive affinity factor. It's possible that encouraging cognitive affinity is good enough, making this lower priority.
- Social energy -- seems like this can be rolled into willpower.
- Physical energy -- seems like this is not a primary factor.

## Todo

- [x] Avoid willpower depletion. Require <=0 willpower load over the week.
- [x] Compute willpower balance per day.
- [x] Compute cognitive affinity per day
- [x] Visualize cognitive affinity on the calendar
- [x] Visualize willpower balance on the calendar
